# Generated by Django 6.0.3 on 2026-03-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busseat',
            name='floor_choice',
            field=models.CharField(blank=True, choices=[('lower', 'Lower'), ('upper', 'Upper')], max_length=10, null=True),
        ),
    ]
