# Generated by Django 6.0.3 on 2026-03-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0002_busseat_floor_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busseat',
            name='floor_choice',
            field=models.CharField(choices=[('lower', 'Lower'), ('upper', 'Upper')], max_length=10),
        ),
    ]
