# Generated by Django 6.0.3 on 2026-03-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0003_alter_busseat_floor_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busseat',
            old_name='is_window',
            new_name='is_single_one',
        ),
    ]
