# Generated by Django 6.0.3 on 2026-03-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0004_rename_is_window_busseat_is_single_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_ac',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
