# Generated by Django 6.0.3 on 2026-03-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0005_bus_is_ac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busseat',
            name='seat_class',
            field=models.CharField(choices=[('seater', 'Seater'), ('berth', 'Berth')], max_length=20),
        ),
    ]
