# Generated by Django 6.0.3 on 2026-03-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0006_alter_busseat_seat_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busseat',
            name='is_single_one',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
