# Generated by Django 6.0.3 on 2026-03-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0007_alter_busseat_is_single_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busseat',
            name='is_single_one',
            field=models.BooleanField(default=False),
        ),
    ]
