# Generated by Django 6.0.3 on 2026-03-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0008_alter_busseat_is_single_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbooking',
            name='total_food_price',
        ),
        migrations.RemoveField(
            model_name='busbooking',
            name='total_luggage_price',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
