# Generated by Django 6.0.3 on 2026-03-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0009_remove_busbooking_total_food_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='baggage_type',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='meal_type',
        ),
    ]
