# Generated by Django 6.0.3 on 2026-03-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0010_remove_passenger_baggage_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbookingseat',
            name='food_price',
        ),
        migrations.RemoveField(
            model_name='busbookingseat',
            name='luggage_price',
        ),
    ]
