# Generated by Django 6.0.3 on 2026-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], max_length=10),
        ),
    ]
