# Generated by Django 6.0.3 on 2026-03-26 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0002_alter_movie_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshow',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movie_booking.movie'),
        ),
    ]
