# Generated by Django 6.0.3 on 2026-03-27 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0004_city_remove_theatre_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='city',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='theatres', to='movie_booking.city'),
            preserve_default='True',
        ),
    ]
