# Generated by Django 6.0.3 on 2026-03-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0005_theatre_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='city',
        ),
    ]
