# Generated by Django 6.0.3 on 2026-03-27 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0007_theatre_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshowseatavailability',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movie_booking.movieshow'),
        ),
        migrations.AlterField(
            model_name='showseat',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_booking.screen'),
        ),
    ]
