# Generated by Django 6.0.3 on 2026-03-31 13:48

import django.db.models.deletion
import hotel_booking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to=hotel_booking.models.hotel_poster_image_upload_path)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_count', models.IntegerField(blank=True, null=True)),
                ('is_booking_closed', models.BooleanField(default=False)),
                ('is_wifi', models.BooleanField(default=False)),
                ('is_pool', models.BooleanField(default=False)),
                ('is_spa', models.BooleanField(default=False)),
                ('is_restaurant', models.BooleanField(default=False)),
                ('is_gym', models.BooleanField(default=False)),
                ('is_parking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking.category')),
                ('city', models.ForeignKey(blank='False', null='False', on_delete=django.db.models.deletion.CASCADE, related_name='act_stadiums', to='hotel_booking.city')),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=20, unique=True)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('total_room', models.IntegerField(blank=True, null=True)),
                ('total_room_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_booking.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_avl_rooms', to='hotel_booking.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelBookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking.hotelbooking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking.hotelroomavailability')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_signature', models.CharField(max_length=256)),
                ('method', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('wallet', models.CharField(blank=True, max_length=50, null=True)),
                ('vpa', models.CharField(blank=True, max_length=100, null=True)),
                ('international', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField(default=0, help_text='Amount is in paise')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('captured', models.BooleanField(default=False)),
                ('fee', models.PositiveIntegerField(default=0, help_text='Amount is in paise')),
                ('tax', models.PositiveIntegerField(default=0, help_text='Amount is in paise')),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking.hotelbooking')),
            ],
        ),
    ]
