# Generated by Django 6.0.3 on 2026-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='category',
            field=models.CharField(max_length=40),
        ),
    ]
