# Generated by Django 6.0.3 on 2026-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
