# Generated by Django 6.0.3 on 2026-03-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_booking', '0002_alter_coach_coach_number_alter_station_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('train', 'coach_number')},
        ),
    ]
