# Generated by Django 6.0.3 on 2026-03-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_booking', '0003_alter_coach_coach_number_alter_coach_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='train_type',
            field=models.CharField(choices=[('express', 'Express'), ('passenger', 'Passenger'), ('superfast', 'Superfast')], default='EXP', max_length=10),
        ),
    ]
