# Generated by Django 6.0.3 on 2026-03-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_booking', '0004_train_train_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='total_seats',
            field=models.IntegerField(default=0, help_text='Leave Empty it will calculate automatically'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_type',
            field=models.CharField(choices=[('express', 'Express'), ('passenger', 'Passenger'), ('superfast', 'Superfast')], max_length=10),
        ),
    ]
