# Generated by Django 6.0.3 on 2026-03-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_booking', '0005_alter_coach_total_seats_alter_train_train_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainschedule',
            name='starting_price',
        ),
        migrations.AddField(
            model_name='traintrip',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=350, max_digits=10),
            preserve_default=False,
        ),
    ]
