# Generated by Django 6.0.3 on 2026-03-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_booking', '0006_remove_trainschedule_starting_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('waiting', 'Waiting List'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='trainbooking',
            name='total_passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
