# Generated by Django 6.0.3 on 2026-03-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_booking', '0007_alter_trainbooking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainbooking',
            name='total_food_price',
        ),
    ]
