# Generated by Django 6.0.3 on 2026-03-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_booking', '0008_remove_trainbooking_total_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainbooking',
            name='coach_type',
            field=models.CharField(default='A1', max_length=10),
            preserve_default=False,
        ),
    ]
