# Generated by Django 6.0.3 on 2026-03-28 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_booking', '0009_trainbooking_coach_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainbookingseat',
            name='food_price',
        ),
        migrations.AlterField(
            model_name='trainbookingseat',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='train_booking.trainseat'),
        ),
    ]
