# Generated by Django 6.0.3 on 2026-03-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_booking', '0010_remove_trainbookingseat_food_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='meal_type',
        ),
    ]
