# Generated by Django 6.0.3 on 2026-03-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsevent',
            name='title',
            field=models.CharField(default='haii', max_length=100),
            preserve_default=False,
        ),
    ]
