# Generated by Django 6.0.3 on 2026-03-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_booking', '0002_sportsevent_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportseventbooking',
            name='total_persons',
        ),
        migrations.AddField(
            model_name='sportseventbooking',
            name='total_ticket',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
