# Generated by Django 6.0.3 on 2026-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_booking', '0003_remove_sportseventbooking_total_persons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='category',
            field=models.CharField(max_length=40),
        ),
    ]
