# Generated by Django 6.0.3 on 2026-03-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0003_alter_airport_created_at_alter_flight_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightseat',
            name='column',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
