# Generated by Django 6.0.3 on 2026-03-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0004_flightseat_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='total_seats',
        ),
    ]
