# Generated by Django 6.0.3 on 2026-03-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0005_remove_flight_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighttrip',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
