# Generated by Django 6.0.3 on 2026-03-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0006_alter_flighttrip_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighttrip',
            name='available_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
