# Generated by Django 6.0.3 on 2026-03-19 10:44

import django.db.models.deletion
import flight_booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0007_flighttrip_available_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('airline_picture', models.ImageField(blank=True, null=True, upload_to=flight_booking.models.airline_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='flighttrip',
            name='available_seats',
            field=models.IntegerField(blank=True, help_text='leave empty when adding. Automatically update flight seat count.', null=True),
        ),
        migrations.AlterField(
            model_name='flighttrip',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty when adding. Automatic update the low value', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='baby_carrier',
            field=models.CharField(choices=[('none', 'None'), ('single', 'Baby Carrier Single'), ('double', 'Baby Carrier Double')], default='none', help_text='Set as None for default', max_length=20),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='baggage_type',
            field=models.CharField(choices=[('cabin', 'Cabin Baggage (7kg)'), ('checkin', 'Check-in Baggage (15kg)'), ('extra_5', 'Extra 5kg'), ('extra_10', 'Extra 10kg'), ('none', 'No Extra')], default='none', help_text='Set as No Extra for default', max_length=20),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='meal_type',
            field=models.CharField(choices=[('veg', 'Vegetarian Meal'), ('non_veg', 'Non-Vegetarian Meal'), ('vegan', 'Vegan Meal'), ('child', 'Child Meal'), ('none', 'No Meal')], default='none', help_text='Set as No Meals for default', max_length=20),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='wheelchair',
            field=models.CharField(choices=[('none', 'None'), ('door', 'Wheelchair to Aircraft Door'), ('seat', 'Wheelchair to Seat'), ('lift', 'Wheelchair with Lift')], default='none', help_text='Set as None for default', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='flightseat',
            unique_together={('flight', 'seat_number')},
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(default='Airline', on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flight_booking.airline'),
        ),
    ]
