# Generated by Django 6.0.3 on 2026-03-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0010_remove_flight_airline_flight_airline_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline_detail',
        ),
        migrations.DeleteModel(
            name='Airline',
        ),
    ]
