# Generated by Django 6.0.3 on 2026-03-19 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0013_alter_airline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flight_booking.airline'),
        ),
    ]
