# Generated by Django 6.0.3 on 2026-03-19 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0014_flight_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flight_booking.airline'),
        ),
    ]
