# Generated by Django 6.0.3 on 2026-03-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0015_alter_flight_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschedule',
            name='stops',
            field=models.IntegerField(default=0),
        ),
    ]
