# Generated by Django 6.0.3 on 2026-03-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0016_flightschedule_stops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightseat',
            old_name='is_aisle',
            new_name='is_left_aisle',
        ),
        migrations.AddField(
            model_name='flightseat',
            name='is_right_aisle',
            field=models.BooleanField(default=False),
        ),
    ]
