# Generated by Django 6.0.3 on 2026-03-20 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0017_rename_is_aisle_flightseat_is_left_aisle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightseatavailability',
            old_name='confirmed_at',
            new_name='booked_at',
        ),
    ]
