# Generated by Django 6.0.3 on 2026-03-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0018_rename_confirmed_at_flightseatavailability_booked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighttrip',
            name='is_booking_closed',
            field=models.BooleanField(default=False),
        ),
    ]
