# Generated by Django 6.0.3 on 2026-03-20 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0019_flighttrip_is_booking_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightseatavailability',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flight_booking.flighttrip'),
        ),
    ]
