# Generated by Django 6.0.3 on 2026-03-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0020_alter_flightseatavailability_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
