# Generated by Django 6.0.3 on 2026-03-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0021_passenger_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='dob',
            field=models.DateField(),
        ),
    ]
