# Generated by Django 6.0.3 on 2026-03-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0023_flightseatavailability_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
