# Generated by Django 6.0.3 on 2026-03-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0024_flightbooking_cancelled_at_flightbooking_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='error_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
