# Generated by Django 6.0.3 on 2026-03-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0026_payment_razorpay_order_id_alter_flightbooking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightschedule',
            old_name='departure_time',
            new_name='boarding_time',
        ),
    ]
