# Generated by Django 6.0.3 on 2026-03-22 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0027_rename_departure_time_flightschedule_boarding_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='flight_booking.airport')),
            ],
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='boarding_terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarding_schedules', to='flight_booking.terminal'),
        ),
    ]
