# Generated by Django 6.0.3 on 2026-03-22 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0028_terminal_flightschedule_boarding_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschedule',
            name='arrival_terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_schedules', to='flight_booking.terminal'),
        ),
    ]
