# Generated by Django 6.0.3 on 2026-03-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0030_remove_payment_status_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
