# Generated by Django 6.0.3 on 2026-03-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0031_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
